# Generated by Django 2.2.2 on 2021-10-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnimeGenre",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=255, verbose_name="Anime genre")),
            ],
        ),
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Anime title")),
                ("episodes", models.PositiveIntegerField()),
                ("rank", models.PositiveIntegerField(null=True)),
                (
                    "genre",
                    models.ManyToManyField(
                        related_name="genres",
                        to="homework_drf.AnimeGenre",
                        verbose_name="Genres",
                    ),
                ),
            ],
        ),
    ]
