# Generated by Django 2.2.2 on 2021-10-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("homework_drf", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="genre",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="anime_rel",
                to="homework_drf.AnimeGenre",
                verbose_name="Genres",
            ),
        )
    ]
