# Generated by Django 2.2.2 on 2021-10-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Book name")),
                (
                    "page_counter",
                    models.PositiveIntegerField(verbose_name="Number of pages"),
                ),
            ],
            options={"verbose_name_plural": "Books"},
        )
    ]
